[0m17:10:17.839175 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DB2CC4BFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DB2FE9DD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DB2FE9FD10>]}


============================== 17:10:17.854191 | cf2e33f1-e19d-4bf6-a07b-5b95a7ba406c ==============================
[0m17:10:17.854191 [info ] [MainThread]: Running with dbt=1.7.13
[0m17:10:17.871716 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Remya\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init demo_dbt', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:10:17.881390 [debug] [MainThread]: Starter project path: C:\Users\Remya\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m17:10:17.994790 [info ] [MainThread]: 
Your new dbt project "demo_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:10:17.998791 [info ] [MainThread]: Setting up your profile.
[0m17:22:47.798947 [info ] [MainThread]: Profile demo_dbt written to C:\Users\Remya\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:22:47.866115 [debug] [MainThread]: Command `dbt init` succeeded at 17:22:47.866115 after 750.42 seconds
[0m17:22:47.881208 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DB2D7701D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DB2911E810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DB2FE9FD10>]}
[0m17:22:47.886213 [debug] [MainThread]: Flushing usage events
[0m19:28:28.606635 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237B1BAF350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237B165ED90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237B1BAB450>]}


============================== 19:28:28.614613 | 647d8a5f-0cb5-4cc2-8537-001e0fb18f4b ==============================
[0m19:28:28.614613 [info ] [MainThread]: Running with dbt=1.7.13
[0m19:28:28.617121 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Remya\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt test', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:28:28.619154 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:28:28.623144 [debug] [MainThread]: Command `dbt test` failed at 19:28:28.623144 after 0.15 seconds
[0m19:28:28.625138 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237B1B6C250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237B1578590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000237AAE83CD0>]}
[0m19:28:28.627134 [debug] [MainThread]: Flushing usage events
[0m19:28:54.669355 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021813706610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021811008950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218133608D0>]}


============================== 19:28:54.675345 | 91e4e686-ea76-43a9-b575-127bfae93f39 ==============================
[0m19:28:54.675345 [info ] [MainThread]: Running with dbt=1.7.13
[0m19:28:54.677344 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Remya\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:28:54.680337 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:28:54.685324 [debug] [MainThread]: Command `dbt run` failed at 19:28:54.685324 after 0.14 seconds
[0m19:28:54.687320 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218137556D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002181370C550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218133608D0>]}
[0m19:28:54.689835 [debug] [MainThread]: Flushing usage events
[0m15:41:59.600642 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173F2A75550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173F2A5C6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173F2A5C5D0>]}


============================== 15:41:59.607625 | b9442ce3-0743-48df-a081-f724a6069a69 ==============================
[0m15:41:59.607625 [info ] [MainThread]: Running with dbt=1.7.13
[0m15:41:59.610616 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Remya\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:41:59.612611 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:41:59.616353 [debug] [MainThread]: Command `dbt run` failed at 15:41:59.616353 after 0.13 seconds
[0m15:41:59.617350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173F2A4AB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173F2A41F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173EBEB1A10>]}
[0m15:41:59.618348 [debug] [MainThread]: Flushing usage events
